# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PHP-HTTPBuildQuery
version:      0.03
version_from: HTTPBuildQuery.pm
installdirs:  site
requires:
    URI::Escape:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
